# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.gis.db.models.fields
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('location', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('username', models.CharField(unique=True, max_length=255)),
                ('account_created_flag', models.BooleanField(default=False)),
                ('account_created_date', models.DateTimeField(null=True, blank=True)),
                ('blacklisted_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DeactivatedUserLog',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_deactivated_user_log_id', models.BigIntegerField(default=1)),
                ('latitude', models.FloatField(null=True, blank=True)),
                ('longitude', models.FloatField(null=True, blank=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, null=True, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(related_name='deactivate_user_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ForgotPasswordRequest',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user_forgot_password_id', models.BigIntegerField(default=1)),
                ('user_email', models.EmailField(max_length=75)),
                ('reset_password_security_code', models.CharField(max_length=255, null=True, blank=True)),
                ('reset_password_security_code_used_flag', models.BooleanField(default=False)),
                ('date_used', models.DateTimeField(null=True, blank=True)),
                ('user_signed_in_after_without_using_flag', models.BooleanField(default=False)),
                ('date_signed_in_without_using', models.DateTimeField(null=True, blank=True)),
                ('forgot_password_request_latitude', models.FloatField(null=True, blank=True)),
                ('forgot_password_request_longitude', models.FloatField(null=True, blank=True)),
                ('forgot_password_request_point', django.contrib.gis.db.models.fields.PointField(srid=4326, null=True, blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(related_name='forgot_password_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('gender', models.CharField(max_length=1, choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Other')])),
                ('yap_count', models.BigIntegerField(default=0)),
                ('listen_count', models.BigIntegerField(default=0)),
                ('subscribing_users_count', models.BigIntegerField(default=0)),
                ('subscribing_libraries_count', models.BigIntegerField(default=0)),
                ('subscriber_users_count', models.BigIntegerField(default=0)),
                ('description', models.CharField(max_length=255, null=True, blank=True)),
                ('profile_picture_flag', models.BooleanField(default=False)),
                ('profile_picture_path', models.CharField(max_length=255, null=True, blank=True)),
                ('profile_picture_cropped_flag', models.BooleanField(default=False)),
                ('profile_picture_cropped_path', models.CharField(max_length=255, null=True, blank=True)),
                ('web_cover_picture_1_flag', models.BooleanField(default=False)),
                ('web_cover_picture_1_path', models.CharField(max_length=255, null=True, blank=True)),
                ('web_cover_picture_2_flag', models.BooleanField(default=False)),
                ('web_cover_picture_2_path', models.CharField(max_length=255, null=True, blank=True)),
                ('web_cover_picture_3_flag', models.BooleanField(default=False)),
                ('web_cover_picture_3_path', models.CharField(max_length=255, null=True, blank=True)),
                ('date_of_birth', models.DateField(null=True, blank=True)),
                ('url', models.URLField(max_length=255, null=True, blank=True)),
                ('color_1', models.CharField(max_length=255, null=True, blank=True)),
                ('color_2', models.CharField(max_length=255, null=True, blank=True)),
                ('color_3', models.CharField(max_length=255, null=True, blank=True)),
                ('phone_number', models.CharField(max_length=20, null=True, blank=True)),
                ('high_security_account_flag', models.BooleanField(default=False)),
                ('verified_account_flag', models.BooleanField(default=False)),
                ('content_provider_approved_date', models.DateField(null=True, blank=True)),
                ('is_reverse_chronological_order_for_libraries', models.BooleanField(default=True)),
                ('is_privileged', models.BooleanField(default=False)),
                ('is_content_provider', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_user_deleted', models.BooleanField(default=False)),
                ('user_deleted_date', models.DateField(null=True, blank=True)),
                ('city', models.ForeignKey(related_name='profile_user_city', blank=True, to='location.City', null=True)),
                ('country', models.ForeignKey(related_name='profile_user_country', blank=True, to='location.Country', null=True)),
                ('us_state', models.ForeignKey(related_name='profile_user_state', blank=True, to='location.USState', null=True)),
                ('us_zip_code', models.ForeignKey(related_name='profile_user_zip_code', blank=True, to='location.USZIPCode', null=True)),
                ('user', models.OneToOneField(related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('device_computer_flag', models.BooleanField(default=False)),
                ('device_computer_ip', models.CharField(max_length=255, null=True, blank=True)),
                ('device_ios_flag', models.BooleanField(default=False)),
                ('device_ios_token', models.CharField(max_length=255, null=True, blank=True)),
                ('device_android_flag', models.BooleanField(default=False)),
                ('device_android_registration_id', models.CharField(max_length=255, null=True, blank=True)),
                ('session_manually_closed_flag', models.BooleanField(default=False)),
                ('session_logged_out_flag', models.BooleanField(default=False)),
                ('session_timed_out_flag', models.BooleanField(default=False)),
                ('session_created_latitude', models.FloatField(null=True, blank=True)),
                ('sesssion_created_longitude', models.FloatField(null=True, blank=True)),
                ('session_created_point', django.contrib.gis.db.models.fields.PointField(srid=4326, null=True, blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('notify_for_subscribed_libraries', models.BooleanField(default=True)),
                ('notify_for_subscribed_users', models.BooleanField(default=True)),
                ('notify_for_breaking_news', models.BooleanField(default=True)),
                ('notify_for_celebrities', models.BooleanField(default=True)),
                ('notify_for_yapster', models.BooleanField(default=True)),
                ('facebook_connection_flag', models.BooleanField(default=False)),
                ('facebook_account_id', models.BigIntegerField(null=True, blank=True)),
                ('facebook_page_connection_flag', models.BooleanField(default=False)),
                ('facebook_page_id', models.BigIntegerField(null=True, blank=True)),
                ('facebook_share_reyap', models.BooleanField(default=False)),
                ('twitter_connection_flag', models.BooleanField(default=False)),
                ('twitter_account_id', models.BigIntegerField(null=True, blank=True)),
                ('twitter_share_reyap', models.BooleanField(default=False)),
                ('google_plus_connection_flag', models.BooleanField(default=False)),
                ('google_plus_account_id', models.BigIntegerField(null=True, blank=True)),
                ('google_plus_share_reyap', models.BooleanField(default=False)),
                ('linkedin_connection_flag', models.BooleanField(default=False)),
                ('linkedin_account_id', models.BigIntegerField(null=True, blank=True)),
                ('linkedin_share_reyap', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UserFunctions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_user_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(related_name='functions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.BigIntegerField(serialize=False, primary_key=True)),
                ('first_name', models.CharField(max_length=30, blank=True)),
                ('last_name', models.CharField(max_length=30, blank=True)),
                ('gender', models.CharField(max_length=1, choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Other')])),
                ('email', models.EmailField(max_length=75)),
                ('phone_number', models.CharField(max_length=20, null=True, blank=True)),
                ('username', models.CharField(max_length=30, null=True, blank=True)),
                ('description', models.CharField(max_length=255, null=True, blank=True)),
                ('profile_picture_flag', models.BooleanField(default=False)),
                ('profile_picture_path', models.CharField(max_length=255, null=True, blank=True)),
                ('profile_picture_cropped_flag', models.BooleanField(default=False)),
                ('profile_picture_cropped_path', models.CharField(max_length=255, null=True, blank=True)),
                ('web_cover_picture_1_flag', models.BooleanField(default=False)),
                ('web_cover_picture_1_path', models.CharField(max_length=255, null=True, blank=True)),
                ('web_cover_picture_2_flag', models.BooleanField(default=False)),
                ('web_cover_picture_2_path', models.CharField(max_length=255, null=True, blank=True)),
                ('web_cover_picture_3_flag', models.BooleanField(default=False)),
                ('web_cover_picture_3_path', models.CharField(max_length=255, null=True, blank=True)),
                ('date_of_birth', models.DateField(null=True, blank=True)),
                ('url', models.URLField(max_length=255, null=True, blank=True)),
                ('color_1', models.CharField(max_length=255, null=True, blank=True)),
                ('color_2', models.CharField(max_length=255, null=True, blank=True)),
                ('color_3', models.CharField(max_length=255, null=True, blank=True)),
                ('last_account_modified_date', models.DateTimeField(auto_now_add=True)),
                ('high_security_account_flag', models.BooleanField(default=False)),
                ('verified_account_flag', models.BooleanField(default=False)),
                ('facebook_connection_flag', models.BooleanField(default=False)),
                ('facebook_account_id', models.BigIntegerField(null=True, blank=True)),
                ('facebook_page_connection_flag', models.BooleanField(default=False)),
                ('facebook_page_id', models.BigIntegerField(null=True, blank=True)),
                ('twitter_connection_flag', models.BooleanField(default=False)),
                ('twitter_account_id', models.BigIntegerField(null=True, blank=True)),
                ('google_plus_connection_flag', models.BooleanField(default=False)),
                ('google_plus_account_id', models.BigIntegerField(null=True, blank=True)),
                ('linkedin_connection_flag', models.BooleanField(default=False)),
                ('linkedin_account_id', models.BigIntegerField(null=True, blank=True)),
                ('user_created_latitude', models.FloatField(null=True, blank=True)),
                ('user_created_longitude', models.FloatField(null=True, blank=True)),
                ('user_created_point', django.contrib.gis.db.models.fields.PointField(srid=4326, null=True, blank=True)),
                ('notify_for_subscribed_libraries', models.BooleanField(default=True)),
                ('notify_for_subscribed_users', models.BooleanField(default=True)),
                ('notify_for_breaking_news', models.BooleanField(default=True)),
                ('notify_for_celebrities', models.BooleanField(default=True)),
                ('notify_for_yapster', models.BooleanField(default=True)),
                ('content_provider_approved_date', models.DateField(null=True, blank=True)),
                ('is_privileged', models.BooleanField(default=False)),
                ('is_content_provider', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_user_deleted', models.BooleanField(default=False)),
                ('user_deleted_date', models.DateField(null=True, blank=True)),
                ('city', models.ForeignKey(related_name='city', blank=True, to='location.City', null=True)),
                ('country', models.ForeignKey(related_name='country', blank=True, to='location.Country', null=True)),
                ('us_state', models.ForeignKey(related_name='us_state', blank=True, to='location.USState', null=True)),
                ('us_zip_code', models.ForeignKey(related_name='us_zip_code', blank=True, to='location.USZIPCode', null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
    ]
